import Head from 'next/head'
import Image from 'next/image'
import BottomJobCard from '../components/BottomJobCard'
import FeaturedJobs from '../components/FeaturedJobs'
import Hero from '../components/Hero'
import JobCard from '../components/JobCard'
import Navbar from '../components/Navbar'
import SearchBar from '../components/SearchBar'
import SideJobCard from '../components/SideJobCard'
import { API_URL } from '../config'
//import styles from '../styles/Home.module.css'

export default function Home({jobs}) {
  console.log(jobs)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <section className="bg-background">
    
      <Hero/>
      <div className="container mx-auto w-full md:max-w-7xl">
      <SearchBar/>
      </div>
      <div className="container mx-auto max-w-7xl">
      <h2 className="text-xl sm:text-xl md:text-2xl lg:text-2xl xl:text-2xl  text-white">Featured Gigs</h2>
      <div className="container mx-auto md:flex  items-stretch justify-between">
      <div>{jobs.data.map((job) => (
      
        <FeaturedJobs key={job.id} job={job}  />
    ))}
      </div> 
      <SideJobCard/>
      
      

      </div>
      
     
      </div>
      <div className="container mx-auto max-w-7xl">
      <div className="flex items-stretch justify-center">
      <BottomJobCard/>
      </div>
      </div>
      </section>

      <footer>
       
      </footer>
    </div>
  )
}
export async function getServerSideProps() {

  const jobRes = await fetch(`${API_URL}/jobs?populate=*&sort=featured:desc&sort=publishedAt:desc`)
  const jobs=await jobRes.json()

return{
  props:{jobs}
}
}

