import Head from 'next/head'
import Image from 'next/image'
import BottomJobCard from '../../components/BottomJobCard'
import FeaturedJobs from '../../components/FeaturedJobs'
import Hero from '../../components/Hero'
import JobCard from '../../components/JobCard'
import Navbar from '../../components/Navbar'
import SearchBar from '../../components/SearchBar'
import SideJobCard from '../../components/SideJobCard'
import { API_URL } from '../../config'
import Select from 'react-select'
import { useQuery, useQueryClient } from 'react-query'
import { useState } from 'react'
import { useEffect } from 'react'
//import styles from '../styles/Home.module.css'


export default function Filter({jobs,categories}) {



  const fetchCategory=async(key)=>{
    console.log(key)
    const res= await fetch(`${API_URL}/jobs?populate=*?filters[category][$eq]=${categoryValue}`)
    return res.json()
  }




  console.log(jobs)
  console.log(categories)

  
  let options=[]

  for (var i = 0; i < categories.data.length; ++i) {
    options.push({"value": categories.data[i].attributes.name,"label": categories.data[i].attributes.name,"id":categories.data[i].id})
  }
  console.log(options)


  // Use Query Setuo--------------------------------------------------
  const [categoryValue, setCategoryValue]=useState(null)
  const [categoryID, setCategoryID]=useState(null)
  const queryClient=useQueryClient()
  const {data, status}=useQuery(['category',categoryValue],fetchCategory, {initialData:jobs})

console.log (categoryID)
  
  const handleCategories=(values)=>{
    
      setCategoryValue(values)
     
      console.log(values)
  }

 




  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <section className="bg-background">
     

      <Hero/>
      <div className="container mx-auto w-full md:max-w-7xl">
      <SearchBar/>
      
      <div className="text-black">
        
        <Select
               
                options={options} 
               getOptionLabel={options=>options.label}
                getOptionValue={options=options.id}
                instanceID="categories"
                isMulti
                placeholder="Filter by Category"
                onChange={value=>setCategoryID(value.id)}
                />
      
      </div>
      </div>
      <div className="container mx-auto max-w-7xl">
      <h2 className="text-xl sm:text-xl md:text-2xl lg:text-2xl xl:text-2xl  text-white">Featured Gigs</h2>
      <div className="container mx-auto md:flex  items-stretch justify-between">
      <div>
      
        { data.data.map((job) => (
      
        <FeaturedJobs key={job.id} job={job} />
    ))}
      </div> 
      <SideJobCard/>
      
      

      </div>
      
     
      </div>
      <div className="container mx-auto max-w-7xl">
      <div className="flex items-stretch justify-center">
      <BottomJobCard/>
      </div>
      </div>
      </section>

      <footer>
       
      </footer>
    </div>
  )
}
export async function getServerSideProps() {

  const jobRes = await fetch(`${API_URL}/jobs?populate=*&sort=featured:desc&sort=publishedAt:desc`)
  const jobs=await jobRes.json()
  const categoriesRes=await fetch(`${API_URL}/categories?populate=*`)
  const categoriesData=await categoriesRes.json()
return{
  props:{jobs:jobs,
    categories:categoriesData
}
}
}

