import Head from 'next/head'
import Image from 'next/image'
import FeaturedJobs from '../../components/FeaturedJobs'
import Hero from '../../components/Hero'
import Navbar from '../../components/Navbar'
import SearchBar from '../../components/SearchBar'
import SideJobCard from '../../components/SideJobCard'
import { API_URL } from '../../config'
import qs from 'qs'
import { useRouter } from 'next/router'

//import styles from '../styles/Home.module.css'

export default function Search({jobs}) {
  console.log(jobs)
  const router=useRouter()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <section className="bg-background">
    
      <Hero/>
      <div className="container mx-auto max-w-7xl">
      <SearchBar/>
      </div>
      <h1>Search results for "{router.query.term}"</h1>
      <div className="container mx-auto max-w-7xl">

      <div className="container mx-auto flex  items-stretch justify-between">
      <div>{jobs.data.map((job) => (
        <FeaturedJobs key={job.id} job={job} />
      ))}
      </div> 
      <SideJobCard/>
      
      
      </div>
      </div>
      <div className="container mx-auto max-w-7xl">
      <div className="flex items-stretch justify-evenly">
      <SideJobCard/>
      <SideJobCard/>
      </div>
      </div>
      </section>

      <footer>
       
      </footer>
    </div>
  )
}
export async function getServerSideProps({query:{term}}) {
    const query = qs.stringify({
        filters: {
            
          description: {
            $containsi:term,
          },
         
        
        positionTitle: {
            $containsi:term }
     } })
 
        const jobRes = await fetch(`${API_URL}/jobs?${query}`)
  const jobs=await jobRes.json()

return{
  props:{jobs}
}
}

